services:
  pdfchat:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pdfchat
    command: streamlit run app.py  --server.address 0.0.0.0 --server.port 8999 --server.fileWatcherType none
    ports:
      - "8999:8999"
